---
- hosts: localhost
  collections:
    - dynatrace_innovationlab.collection
  vars:
    tenant_url: 'https://XXXXXX.live.dynatrace.com'
    api_token: 'XXXXX'

  tasks:
  - include_role:
      name: dynatrace_problem_comment
    vars:
      problem_id: 'XXXX'
      comment: 'Hello from Ansible'
      user: 'your@email.com'
      context: 'Ansible'
