### REQUIRED

# this can be a company/brand/organization or product namespace
# under which all content lives
namespace: dynatrace_innovationlab


# the designation of this specific collection
name: dynatrace_collection


# semantic versioning compliant version designation
version: 1.0.5

# the filename for the readme file which can be either markdown (.md)
readme: README.md


# a list of the collection's content authors
# Ex: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors:
- Juergen Etzlstorfer <juergen.etzlstorfer@dyntrace.com>


### OPTIONAL but strongly advised

# short summary of the collection
description: Collection comprising capabilities to send comments to a problem ticket and send custom deployment information.


# Either a single valid SPDX license identifier or a list of valid SPDX license
# identifiers, see https://spdx.org/licenses/. Could also set `license_file`
# instead to point to the file the specifies the license in the collection
# directory.
license: Apache-2.0


# list of keywords you want to associate the collection
# with for indexing/search systems
tags: 
  - dynatrace
  - monitoring
  - deployment


# A dict of dependencies. A dependency is another collection
# this collection requires to be installed for it to be usable.
# The key of the dict is the collection label (namespace.name)
# and the value is a spec for the semver version required.
dependencies: {}


### URLs

# url of originating SCM repository
repository: https://github.com/dynatrace-innovationlab/ansible-collection


# url to online docs
documentation: https://github.com/dynatrace-innovationlab/ansible-collection


# homepage of the collection/project
homepage: https://www.dynatrace.com


# issue tracker url
issues: https://github.com/dynatrace-innovationlab/ansible-collection
